### ISSUE TITLE
Feature Request - Add option to use destination folder instead of file

### ISSUE THREAD

**Issue by Chris2011** [mattstyles/grunt-jsonmin#1]
My case is a folder with localized json files (de.json, en.json, etc.)
What I want is to minify each file into a seperate folder.

As I tried this:

```
    jsonmin: {
        dev: {
          options: {
            stripWhitespace: true,
            stripComments: true
          },
          files: {
            "<%= meta.jsonPath %>min": ['<%= meta.jsonPath %>*.json']
          }
       }
    },
```

Running "jsonmin:dev" (jsonmin) task
Warning: Unable to write "path/min" file (Error code: EISDIR). Use --force to continue.

So I think at the moment its not possible to use this. I don't want to write this:

```
    files: {
       "<%= meta.jsonPath %>min/de.json": '<%= meta.jsonPath %>de.json',
       "<%= meta.jsonPath %>min/en.json": '<%= meta.jsonPath %>en.json',
       "<%= meta.jsonPath %>min/es.json": '<%= meta.jsonPath %>es.json',
       "<%= meta.jsonPath %>min/nl.json": '<%= meta.jsonPath %>nl.json',
    }
```

because the gruntfile will more and more unreadable and when we will put in a new language we have to update the gruntfile.

So please add a feature that we can use multiple files as an array to put it out into a destination folder.

Regards

Chris

**Comment by OrangeDuck91** [comment]
I'm a bit late, but this could be useful for someone else. There is a workaround : 

```
jsonmin: {
        dev: {
          options: {
            stripWhitespace: true,
            stripComments: true
          },
         files: [
                    {
                        expand: true,
                        cwd: '<%= app.source %>/langages',
                        src: '*.json',
                        dest: '<%= app.dist %>/langages'
                    }]
       }
    },
```

This will run the jsonmin command on every file in '<%= app.source %>/langages' directory.

**Comment by mattstyles** [comment]
I'll happily merge any decent PR to make this process easier.

I havent touched grunt for years so I'm probably not in the best position to attempt any changes myself.

**Comment by Chris2011** [comment]
Unfortunately, I don't use grunt anymore too. So maybe you can tag this ticket with help-wanted and it can still be open. Thx :)
